- name: Deploy index.html and configure Apache on Amazon Linux 2023
  hosts: ec1
  become: yes
  tasks:
    - name: Install httpd, firewalld, mod_ssl, and Certbot
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - firewalld
        - mod_ssl
        - certbot
        - python3-certbot-apache

    - name: Ensure firewalld is running
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Ensure firewalld allows HTTP and HTTPS
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 80/tcp
        - 443/tcp

    - name: Ensure httpd is running
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create web root directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copy index.html to the EC1 instance
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Configure Apache virtual host (HTTP only)
      copy:
        content: |
          <VirtualHost *:80>
              ServerName mohdmiqdad.site
              DocumentRoot /var/www/html
              <Directory /var/www/html>
                  AllowOverride All
                  Require all granted
              </Directory>
          </VirtualHost>
        dest: /etc/httpd/conf.d/vhost.conf
        mode: '0644'
      notify: Reload httpd

    - name: Ensure no HTTP to HTTPS redirection (optional, as not needed)
      file:
        path: /var/www/html/.htaccess
        state: absent

    - name: Create SSL backup directory
      file:
        path: /var/sslbckp
        state: directory
        mode: '0755'

    - name: Backup vhost_https.conf
      copy:
        src: /etc/httpd/conf.d/vhost_https.conf
        dest: /var/sslbckp/vhost_https.conf
        remote_src: yes
        mode: '0644'
      ignore_errors: yes  # In case the file doesn't exist yet

    - name: Backup letsencrypt directory
      copy:
        src: /etc/letsencrypt/
        dest: /var/sslbckp/letsencrypt/
        remote_src: yes
        mode: '0700'
        directory_mode: '0700'
      ignore_errors: yes  # In case the directory doesn't exist

    - name: Restore vhost_https.conf to original location
      copy:
        src: /var/sslbckp/vhost_https.conf
        dest: /etc/httpd/conf.d/vhost_https.conf
        remote_src: yes
        mode: '0644'
      ignore_errors: yes  # In case the backup file doesn't exist
      notify: Reload httpd

    - name: Restore letsencrypt directory to original location
      copy:
        src: /var/sslbckp/letsencrypt/
        dest: /etc/letsencrypt/
        remote_src: yes
        mode: '0700'
        directory_mode: '0700'
      ignore_errors: yes  # In case the backup directory doesn't exist

    - name: Verify Apache is listening on port 80 and 443
      command: netstat -tuln | grep ':80\|:443'
      register: netstat_output
      changed_when: false
      failed_when: "'LISTEN' not in netstat_output.stdout"

    - name: Verify index.html exists
      stat:
        path: /var/www/html/index.html
      register: index_stat
      failed_when: not index_stat.stat.exists

  handlers:
    - name: Reload httpd
      service:
        name: httpd
        state: reloaded
