- name: Deploy index.html to EC2
  hosts: ec1
  become: yes
  tasks:
    - name: Copy index.html to the EC1 instance
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        mode: '0644'
