- name: Deploy index.html to EC2
  hosts: ansible-target1
  become: yes  # Run as sudo, if needed
  tasks:
    - name: Copy index.html to the EC1 instance
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        mode: '0644'
