---
- hosts: web
  become: yes
  tasks:
    - name: Copy updated index.html to web server
      copy:
        src: "{{ playbook_dir }}/../index.html"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
